import React from 'react';

export interface AtlasReport {
    query: string;
    market_posture: string;
    opportunity_themes: string[];
    governance_flags: string[];
    scenarios_considered: string[];
    action_plan: string;
    confidence_score: number;
}

interface ReportViewProps {
    report: AtlasReport;
}

const ReportView: React.FC<ReportViewProps> = ({ report }) => {
    return (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">

            {/* 1. Market Posture Header */}
            <div className="flex items-start justify-between bg-terminal-surface border border-terminal-border rounded-lg p-6">
                <div>
                    <h2 className="text-terminal-text-muted text-xs uppercase tracking-widest mb-2">Council Market Posture</h2>
                    <div className="text-2xl font-bold font-mono text-terminal-text">
                        {report.market_posture}
                    </div>
                    <div className="mt-2 flex gap-2">
                        {report.opportunity_themes.map(theme => (
                            <span key={theme} className="px-2 py-1 bg-terminal-accent/10 border border-terminal-accent/30 text-terminal-accent text-xs rounded">
                                💡 {theme}
                            </span>
                        ))}
                    </div>
                </div>
                <div className="text-right">
                    <div className="text-3xl font-bold text-terminal-text">{Math.round(report.confidence_score * 100)}%</div>
                    <div className="text-xs text-terminal-text-muted">Consensus Confidence</div>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

                {/* 2. Main Action Plan */}
                <div className="md:col-span-2 bg-terminal-surface border border-terminal-border rounded-lg p-6 relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-1 h-full bg-terminal-accent"></div>
                    <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                        <span>📜</span> Plan Atlas Recommendation
                    </h3>
                    <div className="prose prose-invert prose-sm max-w-none font-sans text-terminal-text/90 leading-relaxed whitespace-pre-wrap">
                        {report.action_plan}
                    </div>
                    <div className="mt-6 pt-4 border-t border-terminal-border/50 text-[10px] text-terminal-text-muted italic">
                        Generated by Atlas Council V1.0 • Verified by Guardrail Middleware
                    </div>
                </div>

                {/* 3. Governance Sidebar */}
                <div className="space-y-4">

                    {/* Flags */}
                    <div className="bg-terminal-bg border border-terminal-border rounded-lg p-4">
                        <h4 className="text-xs font-bold text-terminal-text-muted uppercase mb-3">Governance Flags</h4>
                        <ul className="space-y-2">
                            {report.governance_flags.map((flag, i) => {
                                const isCritical = flag.includes('CRITICAL');
                                const isWarning = flag.includes('WARNING');
                                const isMacro = flag.includes('MACRO');

                                let borderColor = 'border-terminal-border';
                                let textColor = 'text-terminal-text';
                                let icon = 'ℹ️';

                                if (isCritical) { borderColor = 'border-red-900'; textColor = 'text-red-400'; icon = '🛑'; }
                                else if (isWarning) { borderColor = 'border-amber-900'; textColor = 'text-amber-400'; icon = '⚠️'; }
                                else if (isMacro) { borderColor = 'border-blue-900'; textColor = 'text-blue-400'; icon = '🌐'; }

                                return (
                                    <li key={i} className={`p-2 rounded border ${borderColor} bg-terminal-surface/50 text-xs ${textColor} flex gap-2 items-start`}>
                                        <span className="mt-0.5">{icon}</span>
                                        <span>{flag}</span>
                                    </li>
                                );
                            })}
                            {report.governance_flags.length === 0 && (
                                <li className="text-xs text-green-500 flex gap-2">
                                    <span>✅</span> No governance violations detected.
                                </li>
                            )}
                        </ul>
                    </div>

                    {/* Scenarios */}
                    <div className="bg-terminal-bg border border-terminal-border rounded-lg p-4">
                        <h4 className="text-xs font-bold text-terminal-text-muted uppercase mb-3">Scenarios Factored</h4>
                        <div className="flex flex-wrap gap-2">
                            {report.scenarios_considered.map(s => (
                                <span key={s} className="px-2 py-1 bg-gray-800 text-gray-300 border border-gray-700 text-[10px] rounded">
                                    🎲 {s}
                                </span>
                            ))}
                        </div>
                    </div>

                </div>
            </div>

        </div>
    );
};

export default ReportView;
